import { and, eq, sql } from "drizzle-orm";
import { db } from "../db";
import { gameCoachSummary } from "../db/schema";

/**
 * Post-game coaching summaries, generated by an LLM from each player's own
 * Stockfish-derived performance in a finished game. See lib/llm/coach.ts for
 * what goes into a summary and lib/llm/groq.ts for who generates it — this
 * module only knows about the queue and the storage.
 *
 * There is no interim "claimed"/"running" state here, unlike
 * lib/services/analysis.ts's game_analysis queue: a coaching attempt either
 * finishes (recordCoachSummary) or doesn't (recordCoachFailure, or the
 * process dies before either runs), and in both non-success cases the next
 * poll simply tries again because no row — or a row with a null summary —
 * still reads as "needs coaching." Recording is an idempotent upsert, so two
 * workers racing on the same pair would waste one Groq call, never corrupt
 * data; that's a low enough stake, at this club's single-worker scale, not
 * to warrant the same for-update-skip-locked ceremony game_analysis uses.
 */

export type CoachClaim = { gameId: number; userId: number };

type CandidateRow = {
  game_id: number;
  white_id: number;
  black_id: number;
  white_summary: string | null;
  black_summary: string | null;
};

/**
 * The oldest finished, analysed game with a player still missing a summary,
 * and which of its two players needs one — white is offered first if both
 * do, so a follow-up poll picks up black.
 */
export async function claimNextForCoaching(): Promise<CoachClaim | null> {
  const rows = await db.execute(sql`
    select
      g.id as game_id,
      g.white_id,
      g.black_id,
      ws.summary as white_summary,
      bs.summary as black_summary
    from game_analysis ga
    join games g on g.id = ga.game_id
    left join game_coach_summary ws
      on ws.game_id = g.id and ws.user_id = g.white_id
    left join game_coach_summary bs
      on bs.game_id = g.id and bs.user_id = g.black_id
    where ga.status = 'done'
      and (ws.summary is null or bs.summary is null)
    order by ga.finished_at asc
    limit 1
  `);

  const row = (rows as unknown as CandidateRow[])[0];
  if (!row) return null;

  return row.white_summary == null
    ? { gameId: row.game_id, userId: row.white_id }
    : { gameId: row.game_id, userId: row.black_id };
}

/** Store a successful summary, replacing any earlier failed attempt. */
export async function recordCoachSummary(
  gameId: number,
  userId: number,
  summary: string,
  model: string,
): Promise<void> {
  await db
    .insert(gameCoachSummary)
    .values({ gameId, userId, summary, model, error: null, generatedAt: new Date() })
    .onConflictDoUpdate({
      target: [gameCoachSummary.gameId, gameCoachSummary.userId],
      set: { summary, model, error: null, generatedAt: new Date() },
    });
}

/** Record a failed attempt. `summary` stays null, so it is retried later. */
export async function recordCoachFailure(
  gameId: number,
  userId: number,
  message: string,
): Promise<void> {
  const error = message.slice(0, 500);
  await db
    .insert(gameCoachSummary)
    .values({ gameId, userId, summary: null, model: null, error, generatedAt: null })
    .onConflictDoUpdate({
      target: [gameCoachSummary.gameId, gameCoachSummary.userId],
      set: { error },
    });
}

/** The stored summary for one player in one game, or null if none exists yet. */
export async function summaryFor(gameId: number, userId: number): Promise<string | null> {
  const [row] = await db
    .select({ summary: gameCoachSummary.summary })
    .from(gameCoachSummary)
    .where(and(eq(gameCoachSummary.gameId, gameId), eq(gameCoachSummary.userId, userId)));
  return row?.summary ?? null;
}
